# Generated by Django 5.0.7 on 2024-07-29 00:18

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dog_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('kind', models.CharField(max_length=100)),
                ('blood', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=users.models.image_upload_path)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
