# Generated by Django 5.0.7 on 2024-08-02 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_reservation_dog'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dog',
        ),
    ]

