# Generated by Django 5.0.7 on 2024-07-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blood',
            field=models.CharField(choices=[('DEA 1-', 'DEA 1-'), ('DEA 1.1', 'DEA 1.1'), ('DEA 1.2', 'DEA 1.2'), ('DEA 3', 'DEA 3'), ('DEA 4', 'DEA 4'), ('DEA 5', 'DEA 5'), ('DEA 6', 'DEA 6'), ('DEA 7', 'DEA 7')], max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='region',
            field=models.CharField(choices=[('서울', '서울'), ('경기', '경기'), ('인천', '인천'), ('강원', '강원'), ('경상', '경상'), ('충청', '충청'), ('전라', '전라'), ('제주', '제주')], max_length=50),
        ),
    ]
