# Generated by Django 5.0.7 on 2024-07-30 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_recomment'),
        ('community', '0006_rename_image_post_image_1_post_image_2_post_image_3'),
    ]

    operations = [
    ]
