# Generated by Django 5.0.7 on 2024-07-31 21:55

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DogProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dogname', models.CharField(max_length=40)),
                ('gender', models.CharField(blank=True, choices=[('수컷', '수컷'), ('중성화', '중성화'), ('암컷', '암컷')], max_length=10)),
                ('dog_age', models.IntegerField()),
                ('dog_weight', models.CharField(max_length=50)),
                ('dog_blood', models.CharField(choices=[('DEA 1-', 'DEA 1-'), ('DEA 1.1', 'DEA 1.1'), ('DEA 1.2', 'DEA 1.2'), ('DEA 3', 'DEA 3'), ('DEA 4', 'DEA 4'), ('DEA 5', 'DEA 5'), ('DEA 7', 'DEA 7')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to=accounts.models.image_upload_path)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
    ]
