# Generated by Django 5.0.7 on 2024-08-04 21:42

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=accounts.models.image_upload_path)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DogProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dogname', models.CharField(max_length=40)),
                ('gender', models.CharField(blank=True, choices=[('수컷', '수컷'), ('중성화', '중성화'), ('암컷', '암컷')], max_length=10)),
                ('dog_age', models.IntegerField()),
                ('dog_weight', models.FloatField(max_length=50)),
                ('dog_blood', models.CharField(choices=[('DEA 1-', 'DEA 1-'), ('DEA 1.1', 'DEA 1.1'), ('DEA 1.2', 'DEA 1.2'), ('DEA 3', 'DEA 3'), ('DEA 4', 'DEA 4'), ('DEA 5', 'DEA 5'), ('DEA 7', 'DEA 7')], max_length=15)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='accounts.userprofile')),
            ],
        ),
    ]
