# Generated by Django 5.0.7 on 2024-08-05 00:21

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogprofile',
            name='dog_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.image_upload_path),
        ),
    ]
