# Generated by Django 5.0.7 on 2024-07-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_dog_blood'),
    ]

    operations = [
        migrations.CreateModel(
            name='dog_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogname', models.CharField(max_length=40)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('neutered', 'Neutered'), ('female', 'Female')], max_length=10)),
                ('dog_age', models.IntegerField()),
                ('dog_weight', models.IntegerField()),
                ('dog_blood', models.CharField(choices=[('DEA 1-', 'DEA 1-'), ('DEA 1.1', 'DEA 1.1'), ('DEA 1.2', 'DEA 1.2'), ('DEA 3', 'DEA 3'), ('DEA 4', 'DEA 4'), ('DEA 5', 'DEA 5'), ('DEA 7', 'DEA 7')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dog_age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dog_blood',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dog_weight',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dogname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
