# Generated by Django 5.0.7 on 2024-08-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dogprofile_dog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogprofile',
            name='kingdog',
            field=models.BooleanField(default=False),
        ),
    ]
