# Generated by Django 5.0.7 on 2024-08-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_dogprofile_kingdog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogprofile',
            name='kingdog',
            field=models.BooleanField(default=True),
        ),
    ]
