# Generated by Django 5.0.7 on 2024-07-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_dog_profile_remove_profile_dog_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dogname', models.CharField(max_length=40)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('neutered', 'Neutered'), ('female', 'Female')], max_length=10)),
                ('dog_age', models.IntegerField()),
                ('dog_weight', models.IntegerField()),
                ('dog_blood', models.CharField(choices=[('DEA 1-', 'DEA 1-'), ('DEA 1.1', 'DEA 1.1'), ('DEA 1.2', 'DEA 1.2'), ('DEA 3', 'DEA 3'), ('DEA 4', 'DEA 4'), ('DEA 5', 'DEA 5'), ('DEA 7', 'DEA 7')], max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='dog_Profile',
        ),
    ]
