# Generated by Django 5.0.7 on 2024-08-03 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_socialaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialAccount',
        ),
    ]
