# Generated by Django 5.0.7 on 2024-08-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_dogprofile_dog_weight_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogprofile',
            name='dog_weight',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
