# Generated by Django 5.0.7 on 2024-08-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_dogprofile_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogprofile',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
