# Generated by Django 5.0.7 on 2024-07-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_dogprofile_delete_dog_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('수컷', '수컷'), ('중성화', '중성화'), ('암컷', '암컷')], max_length=10),
        ),
    ]
