# Generated by Django 5.0.7 on 2024-08-04 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_dogprofile_owner_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogprofile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='accounts.userprofile'),
        ),
    ]
