# Generated by Django 5.0.7 on 2024-07-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agetest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('UNDER_18M', '18개월 미만'), ('18M_TO_8Y', '18개월~8살'), ('OVER_9Y', '9살 이상')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Diseasetest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_disease', models.CharField(choices=[('YES', '네'), ('NO', '아니요')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Sizetest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('SM', '소형견'), ('LG', '대형견')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccinetest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vaccinated', models.CharField(choices=[('YES', '네'), ('NO', '아니요')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Weighttest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_group', models.CharField(choices=[('UNDER_20KG', '20kg 이하'), ('OVER_20KG', '20kg 이상')], max_length=10)),
            ],
        ),
    ]
