# Generated by Django 5.0.7 on 2024-08-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agetest',
            name='age_group',
            field=models.CharField(choices=[('~18M', '18개월 미만'), ('18M~8Y', '18개월~8살'), ('9Y~', '9살 이상')], max_length=10),
        ),
        migrations.AlterField(
            model_name='diseasetest',
            name='has_disease',
            field=models.CharField(choices=[('네', '네'), ('아니요', '아니요')], max_length=3),
        ),
        migrations.AlterField(
            model_name='sizetest',
            name='size',
            field=models.CharField(choices=[('소형견', '소형견'), ('소형견', '대형견')], max_length=3),
        ),
        migrations.AlterField(
            model_name='vaccinetest',
            name='is_vaccinated',
            field=models.CharField(choices=[('접종', '접종'), ('미접종', '미접종')], max_length=3),
        ),
        migrations.AlterField(
            model_name='weighttest',
            name='weight_group',
            field=models.CharField(choices=[('~20KG', '20kg 이하'), ('20KG~', '20kg 이상')], max_length=10),
        ),
    ]
