# Generated by Django 5.0.7 on 2024-08-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_agetest_age_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizetest',
            name='size',
            field=models.CharField(choices=[('소형견', '소형견'), ('대형견', '대형견')], max_length=3),
        ),
    ]
