# Generated by Django 5.0.7 on 2024-07-27 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_agetest_writer_diseasetest_writer_sizetest_writer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Totaltest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agetest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.agetest')),
                ('diseasetest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.diseasetest')),
                ('sizetest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.sizetest')),
                ('vaccinetest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.vaccinetest')),
                ('weighttest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.weighttest')),
                ('writer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
