# Generated by Django 5.0.7 on 2024-08-05 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_phone'),
        ('main', '0002_rename_writer_agetest_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agetest',
            name='nickname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='diseasetest',
            name='nickname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='sizetest',
            name='nickname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='totaltest',
            name='nickname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='vaccinetest',
            name='nickname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='weighttest',
            name='nickname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
