# Generated by Django 5.0.7 on 2024-08-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_agetest_nickname_alter_diseasetest_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agetest',
            name='age_group',
            field=models.CharField(choices=[('~18M', '18개월 미만이에요'), ('18M~8Y', '18개월 이상 8세 이하에요'), ('9Y~', '9살 이상이에요')], max_length=10),
        ),
        migrations.AlterField(
            model_name='diseasetest',
            name='has_disease',
            field=models.CharField(choices=[('네', '네! 앓았던 적이 있어요'), ('아니요', '아니요! 앓았던 적이 없어요')], max_length=3),
        ),
        migrations.AlterField(
            model_name='vaccinetest',
            name='is_vaccinated',
            field=models.CharField(choices=[('접종', '네! 매월 챙기고 있어요'), ('미접종', '아니요! 매월 챙기지 못했어요')], max_length=3),
        ),
        migrations.AlterField(
            model_name='weighttest',
            name='weight_group',
            field=models.CharField(choices=[('~20KG', '20kg 이하에요'), ('20KG~', '20kg 이상이에요')], max_length=10),
        ),
    ]
