# Generated by Django 5.0.7 on 2024-07-27 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_agetest_id_alter_diseasetest_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totaltest',
            old_name='agetest',
            new_name='age_group',
        ),
        migrations.RenameField(
            model_name='totaltest',
            old_name='diseasetest',
            new_name='has_disease',
        ),
        migrations.RenameField(
            model_name='totaltest',
            old_name='vaccinetest',
            new_name='is_vaccinated',
        ),
        migrations.RenameField(
            model_name='totaltest',
            old_name='sizetest',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='totaltest',
            old_name='weighttest',
            new_name='weight_group',
        ),
    ]
