# Generated by Django 5.0.7 on 2024-08-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_agetest_age_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agetest',
            name='age_group',
            field=models.CharField(choices=[('18개월 미만이에요', '18개월 미만이에요'), ('18개월 이상 8세 이하에요', '18개월 이상 8세 이하에요'), ('9살 이상이에요', '9살 이상이에요')], max_length=20),
        ),
        migrations.AlterField(
            model_name='diseasetest',
            name='has_disease',
            field=models.CharField(choices=[('네! 앓았던 적이 있어요', '네! 앓았던 적이 있어요'), ('아니요! 앓았던 적이 없어요', '아니요! 앓았던 적이 없어요')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vaccinetest',
            name='is_vaccinated',
            field=models.CharField(choices=[('네! 매월 챙기고 있어요', '네! 매월 챙기고 있어요'), ('아니요! 매월 챙기지 못했어요', '아니요! 매월 챙기지 못했어요')], max_length=30),
        ),
        migrations.AlterField(
            model_name='weighttest',
            name='weight_group',
            field=models.CharField(choices=[('20kg 이하에요', '20kg 이하에요'), ('20kg 이상이에요', '20kg 이상이에요')], max_length=20),
        ),
    ]
