# Generated by Django 5.0.7 on 2024-07-28 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_agetest_totaltest_age_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totaltest',
            name='age_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.agetest'),
        ),
        migrations.AlterField(
            model_name='totaltest',
            name='has_disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.diseasetest'),
        ),
        migrations.AlterField(
            model_name='totaltest',
            name='is_vaccinated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vaccinetest'),
        ),
        migrations.AlterField(
            model_name='totaltest',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sizetest'),
        ),
        migrations.AlterField(
            model_name='totaltest',
            name='weight_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.weighttest'),
        ),
    ]
