# Generated by Django 5.0.7 on 2024-08-04 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='time',
            new_name='activeTime',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='selectedDate',
        ),
    ]
