# Generated by Django 5.0.7 on 2024-08-02 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dogprofile'),
        ),
    ]

