# Generated by Django 5.0.7 on 2024-08-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='kingdog_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
