# Generated by Django 5.0.7 on 2024-08-04 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_email'),
        ('hospital', '0002_alter_reservation_activetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='dog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.dogprofile'),
        ),
    ]
