# Generated by Django 5.0.7 on 2024-08-04 21:11

import hospital.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_reservation_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=hospital.models.image_upload_path),
        ),
    ]
