# Generated by Django 5.0.7 on 2024-08-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_reservation_kingdog_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='activeTime',
            field=models.CharField(choices=[('오전 10시', '10시'), ('오후 13시', '13시'), ('오후 15시', '15시')], max_length=10),
        ),
    ]
