# Generated by Django 5.0.7 on 2024-08-04 21:12

import hospital.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_hospital_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=hospital.models.image_upload_path),
        ),
    ]
