# Generated by Django 5.0.7 on 2024-07-27 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_remove_reservation_hospital_reservation_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='hospital',
        ),
        migrations.AddField(
            model_name='reservation',
            name='hospital',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hospital.hospital'),
            preserve_default=False,
        ),
    ]
