# Generated by Django 5.0.7 on 2024-07-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='region',
            field=models.CharField(choices=[(None, '지역'), ('서울', '서울'), ('경기', '경기'), ('인천', '인천'), ('강원', '강원'), ('경상', '경상'), ('충청', '충청'), ('전라', '전라'), ('제주', '제주')], default='지역', max_length=50),
        ),
    ]
