# Generated by Django 5.0.7 on 2024-07-29 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_hospital_region'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dog'),
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
