# Generated by Django 5.0.7 on 2024-07-31 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_dogprofile_dog_weight'),
        ('hospital', '0009_alter_reservation_dog_delete_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dogprofile'),
        ),
    ]
